version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-aggregator:latest
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
